### PR TITLE
Dev to Main

### PR DESCRIPTION
**Pull request by brianpippin**
Need to get the ADEPT online arm deployed, if anything else in review makes it in, that is fine, can always do another deployment tomorrow or Monday.

### CODE REVIEW

**Comment by nextcen-dgemoets** [comment]
In http://localhost:3000/participant-progress-table, I'm seeing the test PID I got assigned in PR https://github.com/NextCenturyCorporation/itm-evaluation-dashboard/pull/183 .  I don't recall seeing it during the review, but maybe I didn't check that page.

Or maybe it's expected to be here?

**Comment by kaitlyn-sharo** [comment]
> In http://localhost:3000/participant-progress-table, I'm seeing the test PID I got assigned in PR #183 . I don't recall seeing it during the review, but maybe I didn't check that page.
> 
> Or maybe it's expected to be here?

I did not exclude it from the progress table, but it should be listed as "Test" there.

**Review by nextcen-dgemoets — APPROVED** [review]
I'm not sure I checked/tested every change, but I didn't encounter any problems.

**Comment by phile-caci** [comment]
> I'm not sure I checked/tested every change, but I didn't encounter any problems.

@nextcen-dgemoets , did you run through "Test Text Scenario"? I'm getting an error, troubleshooting to make sure it's not me

**Comment by phile-caci** [comment]
> > I'm not sure I checked/tested every change, but I didn't encounter any problems.
> 
> @nextcen-dgemoets , did you run through "Test Text Scenario"? I'm getting an error, troubleshooting to make sure it's not me

I think it's me, having security issues on my end

**Comment by nextcen-dgemoets** [comment]
> > I'm not sure I checked/tested every change, but I didn't encounter any problems.
> 
> @nextcen-dgemoets , did you run through "Test Text Scenario"? I'm getting an error, troubleshooting to make sure it's not me

I was able to get a PID assigned and start the text scenario.  Was your error before that?  Should I finish the text scenario and do delegation?

**Comment by nextcen-dgemoets** [comment]
> > > I'm not sure I checked/tested every change, but I didn't encounter any problems.
> > 
> > @nextcen-dgemoets , did you run through "Test Text Scenario"? I'm getting an error, troubleshooting to make sure it's not me
> 
> I was able to get a PID assigned and start the text scenario. Was your error before that? Should I finish the text scenario and do delegation?

To answer my own question, yes.  The errors occur once you complete a scenario.  We're all getting it.

**Pull request merged**
