### PR TITLE
Itm 753 store prolificid

### PR DESCRIPTION
**Pull request by kaitlyn-sharo**
Created a new role: adeptUser
Added two new columns to progress table: prolific id and contact id
Stored two new parameters in the participant log: prolific id and contact id (will only appear for online users)

Only adeptUsers and admins can view prolific id and contact id in the progress table. 

Test to make sure the adeptUser box on the admin page works properly, and that being an adeptUser and not an admin, or an admin and not an adeptUser, or both, works for populating ProlificId and contactID in the progress table.

Make sure if you are not an adept user or admin, you cannot view those two columns. Make sure the download does not include those two columns

### CODE REVIEW

**Review by phile-caci — APPROVED** [review]
LGTM!

1. Test with an Experimenter, Evaluator, Adept User and Admin.  Experimenter/Evaluator only roles could not see new columns.  Adept User and Admin could see the prolific id and contact id. Adept User + Experimenter/ Adept User + Evaluator could see new column, as expected.
2. contactID and prolificID was found in participantLog for online user
3. Download did not contain new columns when not Adept User or Admin.

**Review by dereknop — APPROVED** [review]
worked as described. anyone else reviewing make sure to rebuild your gql container

**Review by nextcen-dgemoets — COMMENTED** [review]
I'm still reviewing this but so far haven't found any problems.  Given that there are two reviewers, feel free to merge.  I may still finish up what I'm looking at.

**Comment by brianpippin** [comment]
> I'm still reviewing this but so far haven't found any problems. Given that there are two reviewers, feel free to merge. I may still finish up what I'm looking at.

Darren - I'm not going to merge this until you sign off on it, so let me know when it is good.

**Comment by nextcen-dgemoets** [comment]
Using [http://localhost:3000/remote-text-survey?adeptQualtrix=true&PROLIFIC_PID=123&ContactID=Bob](http://localhost:3000/remote-text-survey?adeptQualtrix=true&PROLIFIC_ID=123&ContactID=Bob), I only see the Contact ID in the Progress table, not Profilic ID.  Also in the DB `profilicID` is null.  Probably user error.

The ADEPTuser role looks good and worked how I expected.

**Comment by nextcen-dgemoets** [comment]
I tried http://localhost:3000/remote-text-survey?adeptQualtrix=true&PROLIFIC_PID=444&ContactID=Bobby, and got the prolific ID.
I tried [http://localhost:3000/remote-text-survey?adeptQualtrix=true&ContactID=PhiLe&PROLIFIC_PID=8732465293487566&class=Online](http://localhost:3000/remote-text-survey?adeptQualtrix=true&ContactID=PhiLe&PROLIFIC_PID=37246529834756&class=Online) and got a Prolific ID.
But twice I tried [http://localhost:3000/remote-text-survey?adeptQualtrix=true&PROLIFIC_PID=123&ContactID=Bob](http://localhost:3000/remote-text-survey?adeptQualtrix=true&PROLIFIC_ID=123&ContactID=Bob) and didn't get a prolific ID.

itm-753

I assume user error.

**Comment by phile-caci** [comment]
> I tried http://localhost:3000/remote-text-survey?adeptQualtrix=true&PROLIFIC_PID=444&ContactID=Bobby, and got the prolific ID. I tried [http://localhost:3000/remote-text-survey?adeptQualtrix=true&ContactID=PhiLe&PROLIFIC_PID=8732465293487566&class=Online](http://localhost:3000/remote-text-survey?adeptQualtrix=true&ContactID=PhiLe&PROLIFIC_PID=37246529834756&class=Online) and got a Prolific ID. But twice I tried [http://localhost:3000/remote-text-survey?adeptQualtrix=true&PROLIFIC_PID=123&ContactID=Bob](http://localhost:3000/remote-text-survey?adeptQualtrix=true&PROLIFIC_ID=123&ContactID=Bob) and didn't get a prolific ID.
> 
> itm-753
> 
> I assume user error. You can ignore the "Jerry" entry-- that _was_ user error, when I put `PROFILIC` in the URL.

Hey Darren, 

I looked at the link that didn't work... looks like the underlying link has http://localhost:3000/remote-text-survey?adeptQualtrix=true&**PROLIFIC_ID**=123&ContactID=Bob  <- "PROLIFIC_ID" instead of "PROLIFIC_PID"

**Comment by nextcen-dgemoets** [comment]
> I looked at the link that didn't work... looks like the underlying link has http://localhost:3000/remote-text-survey?adeptQualtrix=true&**PROLIFIC_ID**=123&ContactID=Bob <- "PROLIFIC_ID" instead of "PROLIFIC_PID"

Good eyes!  Yes, it was a problem with the original link.

**Review by nextcen-dgemoets — APPROVED** [review]

**Pull request merged**
