### PR TITLE
Dev to Main

### PR DESCRIPTION
**Pull request by brianpippin**
ST is waiting on the session IDs to be able to do the group targets, we need to deploy with what we have because have participants doing surveys Tuesday and Thursday and maybe Wednesday.

### CODE REVIEW

**Comment by dereknop** [comment]
Confirmed that text-based scenario and survey pages are functioning and recording data as expected. The vr page of the survey is recording data properly. I am running into issues on the research pages that I believe are a result of me needing to replace my db today (running probe matcher and will check again)

**Comment by nextcen-dgemoets** [comment]
Got warnings I don't remember seeing, although they may well have been there.  Don't know if they are issues.

Also, a console.log in ReviewTextBased.jsx:40.
```
Warning: Unsupported style property text-align. Did you mean textAlign?
    at td
    at tr
    at tbody
    at table
    at EvaluationIDSTable (http://localhost:3000/static/js/bundle.js:146:3)
    at div
    at div
    at Query (http://localhost:3000/static/js/bundle.js:22905:24)
    at div
    at AdminPage (http://localhost:3000/static/js/bundle.js:244:5)
    at C (http://localhost:3000/static/js/bundle.js:340627:37)
    at Admin (http://localhost:3000/static/js/bundle.js:6978:3)
    at Route (http://localhost:3000/static/js/bundle.js:340410:29)
    at Switch (http://localhost:3000/static/js/bundle.js:340579:29)
    at div
    at div
    at Query (http://localhost:3000/static/js/bundle.js:22905:24)
    at Router (http://localhost:3000/static/js/bundle.js:340082:30)
    at App (http://localhost:3000/static/js/bundle.js:7060:5)
    at ApolloProvider (http://localhost:3000/static/js/bundle.js:22789:19)
    at Provider (http://localhost:3000/static/js/bundle.js:616639:3)
```

```
findDOMNode is deprecated and will be removed in the next major release. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
    at div
    at ButtonBase (http://localhost:3000/static/js/bundle.js:38159:22)
    at WithStyles (http://localhost:3000/static/js/bundle.js:44052:31)
    at ListItem (http://localhost:3000/static/js/bundle.js:39212:33)
    at WithStyles (http://localhost:3000/static/js/bundle.js:44052:31)
    at nav
    at List (http://localhost:3000/static/js/bundle.js:39004:24)
    at WithStyles (http://localhost:3000/static/js/bundle.js:44052:31)
    at div
    at div
    at div
    at SurveyResults (http://localhost:3000/static/js/bundle.js:16761:68)
    at Route (http://localhost:3000/static/js/bundle.js:340410:29)
    at Switch (http://localhost:3000/static/js/bundle.js:340579:29)
    at div
    at div
    at Query (http://localhost:3000/static/js/bundle.js:22905:24)
    at Router (http://localhost:3000/static/js/bundle.js:340082:30)
    at App (http://localhost:3000/static/js/bundle.js:7060:5)
    at ApolloProvider (http://localhost:3000/static/js/bundle.js:22789:19)
    at Provider (http://localhost:3000/static/js/bundle.js:616639:3)
```

**Review by nextcen-dgemoets — APPROVED** [review]
Okay-- Derek fixed the console log, the first warning requires a library update that we don't want to risk now, and the second warning will go away when `https://github.com/NextCenturyCorporation/itm-evaluation-dashboard/pull/126` is merged.

**Comment by phile-caci** [comment]
Just ran through all of ingest... the home page, with latest development),  (metrics eval Program Questions, there are a lot of blank charts now. Anyone else seeing that?

**Comment by nextcen-dgemoets** [comment]
> Just ran through all of ingest... the home page, with latest development), (metrics eval Program Questions, there are a lot of blank charts now. Anyone else seeing that?

Same here; also the values are NaN.

**Comment by kaitlyn-sharo** [comment]
> > Just ran through all of ingest... the home page, with latest development), (metrics eval Program Questions, there are a lot of blank charts now. Anyone else seeing that?
> 
> Same here; also the values are NaN.

Yes for me as well

**Comment by kaitlyn-sharo** [comment]
@phile-caci @nextcen-dgemoets I believe I have pushed a fix for that problem, which was caused by data coming from a place where it really shouldn't have been coming from. I have now separated the data accessing/processing methods into their individual files. Please check that it has resolved for you, and that the participant-level page still works as intended (for both DRE and MRE)

**Comment by nextcen-dgemoets** [comment]
> @phile-caci @nextcen-dgemoets I believe I have pushed a fix for that problem, which was caused by data coming from a place where it really shouldn't have been coming from. I have now separated the data accessing/processing methods into their individual files. Please check that it has resolved for you, and that the participant-level page still works as intended (for both DRE and MRE)

Fixed for me-- nice, quick fix!  Re-approved?

**Review by kaitlyn-sharo — APPROVED** [review]
Everything looks like it's working for me.

Just a reminder that in order for everything to work properly on prod, probe matcher will need to be run with RUN_ALIGNMENT=True

**Review by phile-caci — APPROVED** [review]

**Pull request merged**
