### PR TITLE
Itm 351 more graphs

### PR DESCRIPTION
**Pull request by kaitlyn-sharo**
Added more graphs to question 2 on the home page

### CODE REVIEW

**Comment by nextcen-dgemoets** [comment]
Neither the ticket nor the PR have any description.  I see some new charts in the code-- how do I get to them and are there any success criteria I should be considering?

**Comment by kaitlyn-sharo** [comment]
> Neither the ticket nor the PR have any description. I see some new charts in the code-- how do I get to them and are there any success criteria I should be considering?

Check out question 2 on the homepage. No success criteria.

**Review by nextcen-dgemoets — APPROVED** [review]
Graphs look good.

For my money, I think the tooltips should write out the KDMAs ("Maximization" / "Moral Deserts"), but just a nit, and I suspect "Max" and "MD" is probably used everywhere else.

**Comment by kaitlyn-sharo** [comment]
> Graphs look good.
> 
> For my money, I think the tooltips should write out the KDMAs ("Maximization" / "Moral Deserts"), but just a nit, and I suspect "Max" and "MD" is probably used everywhere else.

Changed the tooltips, I liked the idea

**Review by dereknop — APPROVED** [review]
Looks good to me!

**Review by brianpippin — APPROVED** [review]
Code looks good, and the graphs looked great.

**Pull request merged**
