### PR TITLE
Itm 312 external ta1 server access

### PR DESCRIPTION
**Pull request by phile-caci**
tested on prod. It's on prod now for testing, but a release before this branch gets merged will overwrite config.

**SoarTech**

https://darpaitm.caci.com/soartech/docs

https://darpaitm.caci.com/soartech/api/v1/scenarios

**Adept**

https://darpaitm.caci.com/adept/ui/

https://darpaitm.caci.com/adept/api/v1/scenario/MetricsEval.MD3

### CODE REVIEW

**Comment by nextcen-dgemoets** [comment]
The doc/api links (the first link in the SoarTech and Adept sections in the PR description) appear to be linking to the TA3 APIs.  I imagine they should be showing the respective TA1 APIs?

Also, the link to `MetricsEval.MD3` appears to be showing an old version of the file.  The `state` and `scenes` elements are reversed, and it lacks the "v1.2.0" comment on line 2.

**Comment by phile-caci** [comment]
> The doc/api links (the first link in the SoarTech and Adept sections in the PR description) appear to be linking to the TA3 APIs. I imagine they should be showing the respective TA1 APIs?
> 
> Also, the link to `MetricsEval.MD3` appears to be showing an old version of the file. The `state` and `scenes` elements are reversed, and it lacks the "v1.2.0" comment on line 2.

Yikes.. missed the docs redirect... 

Regarding `MetricsEval.MD3`, I assume this means that the Adept server is out of date on our system, I'll update it now.

**Comment by phile-caci** [comment]
> Also, the link to `MetricsEval.MD3` appears to be showing an old version of the file. The `state` and `scenes` elements are reversed, and it lacks the "v1.2.0" comment on line 2.

@nextcen-dgemoets , for Adept should I be using a branch other than main?  I'm still not see`v1.2.0` : 

`{
    "id": "MetricsEval.MD3",
    "name": "Military Base Fire",
    "scenes": [
`

**Comment by nextcen-dgemoets** [comment]
> @nextcen-dgemoets , for Adept should I be using a branch other than main? I'm still not seeing `v1.2.0` :
> 
> `{ "id": "MetricsEval.MD3", "name": "Military Base Fire", "scenes": [ `

For me, in `main`, `openapi_server/data/scenario/metrics_eval/MetricsEval.MD3.yaml` has the v1.2.0 comment.  It looks like you quoted a JSON file?

[Direct link to file](https://gitlab.com/itm-ta1-adept-shared/adept_server/-/raw/main/openapi_server/data/scenario/metrics_eval/MetricsEval.MD3.yaml?ref_type=heads)

**Comment by phile-caci** [comment]
> For me, in `main`, `openapi_server/data/scenario/metrics_eval/MetricsEval.MD3.yaml` has the v1.2.0 comment. It looks like you quoted a JSON file?
> 
> [Direct link to file](https://gitlab.com/itm-ta1-adept-shared/adept_server/-/raw/main/openapi_server/data/scenario/metrics_eval/MetricsEval.MD3.yaml?ref_type=heads)

ahh, I'm showing the json response to the API get: https://darpaitm.caci.com/adept/api/v1/scenario/MetricsEval.MD3

**Comment by nextcen-dgemoets** [comment]
> ahh, I'm showing the json response to the API get: https://darpaitm.caci.com/adept/api/v1/scenario/MetricsEval.MD3

Ah, okay-- yep, it looks good, then.

**Comment by phile-caci** [comment]
> I ran Kaitlyn's ingest script connecting to the prod servers and it worked beautifully.

awesome, Just chatting with Darren, I dont think I can get TA1's swagger doc to show up.  Since they all (our TA3 API, SoarTech API, Adept API) use /ui or /docs and their (and ours) swagger server always requests (root)/openapi.json for the swagger doc.  They would need to add a context path (i.e. /adept/openapi.json, but currently request it at (root)/open.json) for us to make it work.

The swagger docs probably isn't as important as long as the API's work (which appear to).

I'm going to redirect TA1's swagger doc to 404.

**Comment by brianpippin** [comment]
> > I ran Kaitlyn's ingest script connecting to the prod servers and it worked beautifully.
> 
> awesome, Just chatting with Darren, I dont think I can get TA1's swagger doc to show up. Since they all (our TA3 API, SoarTech API, Adept API) use /ui or /docs and their (and ours) swagger server always requests (root)/openapi.json for the swagger doc. They would need to add a context path (i.e. /adept/openapi.json, but currently request it at (root)/open.json) for us to make it work.
> 
> The swagger docs probably isn't as important as long as the API's work (which appear to).
> 
> I'm going to redirect TA1's swagger doc to 404.

I think that makes sense.  We can give TA1 the option to do that if they want their docs to appear, but that would be a them asking for it, not an us doing it for them.

**Pull request merged**
