### PR TITLE
Itm 644 email login

### PR DESCRIPTION
**Pull request by kaitlyn-sharo**
This PR includes a new login mode for participants who will be taking the text-based scenarios from their own computers ahead of the experiment. 

Run this first: https://github.com/NextCenturyCorporation/itm-ingest/pull/64

Login/Text Scenario tests:
- Redesigned the login page to make it more user-friendly, since it will be front-facing to participants now
   - To test, try all of the pages to make sure they still work and still give the appropriate errors with good styling
- Added /participantText url that should bring you straight to the Text Scenario Login tab (whereas /login brings you to the Sign In tab) 
- LOG OUT before testing any further
- Text Scenario Login tab should require a valid email address (hidden like a password by default, but with option to unhide (click the eye)) and one of the classification options (mil/civ)
- Once the information has been entered and you have pressed "Start", you should be taken directly to the text scenario (without having to put in a PID, vr scenario information, and classification)
- Complete the text scenario and you should see a new ending page that simply says "Thank you... you can close the browser"
- Ensure you can not get to any other page by signing in through the text scenario login
- Ensure you can not get to any page without signing in (making sure nothing broke with this new mode)
- The new mode should have an instructions page, the old mode should function the same as before (NOTE: INSTRUCTIONS PAGE SUBJECT TO CHANGE)

PID Lookup tests:
- Log in as yourself
- See that "PID Lookup" has shown up in the user menu (because you are an admin)
- Go to the administrator page and add yourself as an experimenter, check that the database updates
- Go to the PID lookup page and enter the same email you had used for testing before. Check that the PID that shows up is the same that was logged in userScenarioResults for the text survey you completed
- Enter some invalid emails and make sure no PID shows up

### CODE REVIEW

**Comment by nextcen-dgemoets** [comment]
On the PID Lookup page, clicking the eye gave me a runtime error:
```
Cannot read properties of undefined (reading 'state')
TypeError: Cannot read properties of undefined (reading 'state')
    at toggleVisibility (http://localhost:3000/static/js/bundle.js:2347:30)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:329235:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:329279:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:329336:35)
    at invokeGuardedCallbackAndCatchFirstError (http://localhost:3000/static/js/bundle.js:329350:29)
    at executeDispatch (http://localhost:3000/static/js/bundle.js:333493:7)
    at processDispatchQueueItemsInOrder (http://localhost:3000/static/js/bundle.js:333519:11)
    at processDispatchQueue (http://localhost:3000/static/js/bundle.js:333530:9)
    at dispatchEventsForPlugins (http://localhost:3000/static/js/bundle.js:333539:7)
    at http://localhost:3000/static/js/bundle.js:333699:16
```

**Comment by nextcen-dgemoets** [comment]
> Go to the administrator page and add yourself as an experimenter, check that the database updates

What does this do, exactly?  I was able to look up a PID by email address without having done this.

**Review by phile-caci — COMMENTED** [review]
Except the eye on the PID Lookup page that Darren mentioned, everything else looks good.  (The eye works on the /participantText login page)


Ran through Text Scenario, I got 20249215 as a participantID
```
dashboard> db.participantLog.find({"ParticipantID": 20249215 })
[
  {
    _id: ObjectId('66d8c3ec7b10d2507e7ee586'),
    Type: 'Civ',
    ParticipantID: 20249215,
    'Text-1': 'AD-2',
    'Text-2': 'ST-2',
    'Sim-1': 'AD-3',
    'Sim-2': 'ST-3',
    'Del-1': 'AD-1',
    'Del-2': 'ST-1',
    ADMOrder: 1,
    claimed: true,
    simEntryCount: 0,
    surveyEntryCount: 0,
    textEntryCount: 0,
    hashedEmail: '$2a$10$j0Bpq6e1b0556pu935uBdubnt6ionFqndYCl.reOiHbi9rblObSAi'
  }
]
dashboard> db.userScenarioResults.count({"evalNumber":4, "participantID": "20249215"})
5
```

PID Lookup worked to get my pid, no errors with bad email, just gave me the No PID Found message.

Clicked around the website, as an admin , (/text-based-results updated with my scenario above), and didn't see any issues.

Also ran a second email through the text scenarios, works as expected (/text-based-results updated with this 2nd run also)

**Comment by kaitlyn-sharo** [comment]
> > Go to the administrator page and add yourself as an experimenter, check that the database updates
> 
> What does this do, exactly? I was able to look up a PID by email address without having done this.

That's because you're an admin. Originally, I had made it so only experimenters could access this page, but Brian said admins should also have access. So I just wanted you to check that your database updated to include you as an experimenter

**Comment by kaitlyn-sharo** [comment]
> On the PID Lookup page, clicking the eye gave me a runtime error:
> 
> ```
> Cannot read properties of undefined (reading 'state')
> TypeError: Cannot read properties of undefined (reading 'state')
>     at toggleVisibility (http://localhost:3000/static/js/bundle.js:2347:30)
>     at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:329235:18)
>     at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:329279:20)
>     at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:329336:35)
>     at invokeGuardedCallbackAndCatchFirstError (http://localhost:3000/static/js/bundle.js:329350:29)
>     at executeDispatch (http://localhost:3000/static/js/bundle.js:333493:7)
>     at processDispatchQueueItemsInOrder (http://localhost:3000/static/js/bundle.js:333519:11)
>     at processDispatchQueue (http://localhost:3000/static/js/bundle.js:333530:9)
>     at dispatchEventsForPlugins (http://localhost:3000/static/js/bundle.js:333539:7)
>     at http://localhost:3000/static/js/bundle.js:333699:16
> ```

whoops...bad copy-paste. I'll get on that, thanks

**Review by nextcen-dgemoets — APPROVED** [review]
LGTM!

**Review by phile-caci — APPROVED** [review]
The Eye on http://localhost:3000/pid-lookup is fixed. LGTM!

**Pull request merged**
