### PR TITLE
Text Scenario Test Page

### PR DESCRIPTION
**Pull request by kaitlyn-sharo**
NOTE: PROBABLY NOT FOR THIS ROUND, so not a high priority review (but possibly helpful in the future!)

This PR creates a way for us and OSU to run through the text scenarios without polluting data. The /participantText and /login pages are only available when logged out, currently. This makes a third page, /participantTextTester, that is only available when logged in as an experimenter (OSU) or as an admin (us). To access this page, look at your user dropdown (right under PID Lookup). 

Clicking on it should open up the login page while still keeping your header. 

~~You will see the radio option has changed so ONLY tester is available. Tester has all 24 variations of scenario-ordering (whereas mil and civ only have 12 each).~~

**Update: Now that we do not have classification on the email participant page, this will automatically set entries through this special route to "Test".** 

Check that in the participant id log, when the pid is generated, the type shows up as "Test" in mongo.

Make sure everything else works smoothly.

### CODE REVIEW

**Review by dereknop — APPROVED** [review]
Worked great for me. I see the type marked as tester in the participant log. One thing I noticed (but not part of this ticket) is using an existing email generates the new pid in the participant log even if you hit 'cancel'. So on the results pages I think we are already checking if the results match to a participant id in the participant log, I suppose we will have to add to that condition to specify that the entry it maps to in the participant log cant be of type 'tester'

**Comment by kaitlyn-sharo** [comment]
> Worked great for me. I see the type marked as tester in the participant log. One thing I noticed (but not part of this ticket) is using an existing email generates the new pid in the participant log even if you hit 'cancel'. So on the results pages I think we are already checking if the results match to a participant id in the participant log, I suppose we will have to add to that condition to specify that the entry it maps to in the participant log cant be of type 'Test'

Yes, I agree. I had thought of that but must have forgotten to implement it. I will add a ticket.

**Review by phile-caci — APPROVED** [review]
LGTM!

**Review by brianpippin — APPROVED** [review]
Saw no issues with this one.

**Pull request merged**
