### PR TITLE
redesigned delegation page to follow theme of other pages

### PR DESCRIPTION
**Pull request by kaitlyn-sharo**
Changed selection options to look like other pages, added scroll to top, changed theme/border radius. Overall, just minor changes that make this page flow better with the rest of the application

### CODE REVIEW

**Review by dereknop — APPROVED** [review]
This looks great, and I'm glad the scroll to top button has lived to see another page 😁

**Comment by kaitlyn-sharo** [comment]
> This looks great, and I'm glad the scroll to top button has lived to see another page 😁

I loved the scroll button you made! I'm glad I didn't have to think about it!

**Comment by brianpippin** [comment]
Code looks great, and the page looks great.  I am still not totally in love with the "View Tabulated Data" page.  I am wondering if it would make sense to just have all the checkboxes visible already (not appear when you click "Survey Version" and then always default to the latest survey version only, as I think people are going to be mainly looking for that version.  Thoughts?  (I know it wasn't part of your redesign but just figured while you were revamping this)

**Comment by kaitlyn-sharo** [comment]
> if it would make sense to just have all the checkboxes visible already (not appear when you click "Survey Version" and then always default to the latest survey version only, as I think people are going to be mainly looking for that version. Thoughts? (I know it wasn't part of your redesign but just figured while you were revamping this)

I can do this

**Comment by kaitlyn-sharo** [comment]
> Code looks great, and the page looks great. I am still not totally in love with the "View Tabulated Data" page. I am wondering if it would make sense to just have all the checkboxes visible already (not appear when you click "Survey Version" and then always default to the latest survey version only, as I think people are going to be mainly looking for that version. Thoughts? (I know it wasn't part of your redesign but just figured while you were revamping this)

Completed. Also took care of some errors that were showing up in the console. Must have been some merge conflict at some point. Really strange things

**Review by dereknop — APPROVED** [review]

**Review by brianpippin — APPROVED** [review]

**Pull request merged**
