### PR TITLE
Itm 736 phase1 updates

### PR DESCRIPTION
**Pull request by kaitlyn-sharo**
Updated missing/extra data in tables; added datasource column; fixed download names to be ph1; etc

### CODE REVIEW

**Review by phile-caci — COMMENTED** [review]
Think everything looks good, didn't see any issues issues, except.

1. I think the download for http://localhost:3000/humanProbeData for Phase1 still has `dre` .

**Comment by kaitlyn-sharo** [comment]
> Think everything looks good, didn't see any issues issues, except.
> 
> 1. I think the download for http://localhost:3000/humanProbeData for Phase1 still has `dre` .

Thanks for catching this! Fixed now

**Review by phile-caci — APPROVED** [review]
retested downloads. LGTM!

**Review by brianpippin — APPROVED** [review]
LGTM double checked downloads :)

**Pull request merged**
