### PR TITLE
added missing data to ph1 tables

### PR DESCRIPTION
**Pull request by kaitlyn-sharo**
After running https://github.com/NextCenturyCorporation/itm-ingest/pull/80, I realized that there was data missing from http://localhost:3000/humanProbeData and http://localhost:3000/humanSimParticipant

311 will still be missing some QOL data because they did not complete that scenario, but all other data should appear

### CODE REVIEW

**Comment by dereknop** [comment]
After running ph1 probe matcher with latest mongo backup:

http://localhost:3000/humanSimParticipant:
Screenshot 2024-12-03 at 10 50 02 AM

http://localhost:3000/humanProbeData:
Screenshot 2024-12-03 at 10 51 03 AM


I think this looks good since we only have a handful of participants so far, but I wanted to check.

**Comment by kaitlyn-sharo** [comment]
> After running ph1 probe matcher with latest mongo backup:
> 
> http://localhost:3000/humanSimParticipant: Screenshot 2024-12-03 at 10 50 02 AM
> 
> http://localhost:3000/humanProbeData (zoomed out to 67%): Screenshot 2024-12-03 at 10 51 03 AM
> 
> I think this looks good since we only have a handful of participants so far, but I wanted to check.

That's what I saw, and it seemed good to me. We have 7 participants in the database we're testing with, and all 7 appear

**Review by dereknop — APPROVED** [review]

**Review by brianpippin — APPROVED** [review]
Populated for me!

**Review by phile-caci — COMMENTED** [review]
Mostly looks good, saw just a couple of issues.

1. In [humanSimParticipant](http://localhost:3000/humanSimParticipant), for Phase1
   1. The endpoint for the kdma_profile_graph for **phase1** should be https://darpaitm.caci.com/soartech/api/v1/kdma_profile_graph, (instead of soartech_dre)
2. Both the downloads for Phase1 /humanSimParticipant and /humanProbeData have the `dre` in the file name.  should that be changed to `phase1`

**Comment by kaitlyn-sharo** [comment]
> Mostly looks good, saw just a couple of issues.
> 
> 1. In [humanSimParticipant](http://localhost:3000/humanSimParticipant), for Phase1
>    
>    1. The endpoint for the kdma_profile_graph for **phase1** should be https://darpaitm.caci.com/soartech/api/v1/kdma_profile_graph, (instead of soartech_dre)
> 2. Both the downloads for Phase1 /humanSimParticipant and /humanProbeData have the `dre` in the file name.  should that be changed to `phase1`

Point 2 is fixed in the latest phase 1 PR. I will throw point 1 in there now!

**Pull request merged**
