### PR TITLE
added scalar kdmas to dashboard

### PR DESCRIPTION
**Pull request by kaitlyn-sharo**
Also includes a fix for RQ8, where high/low targets for ph1 were not correct (due to different targets in this eval). 

To test, run [darren's code](https://github.com/NextCenturyCorporation/itm-ingest/pull/81) and make sure for DRE, ST kdmas show up in RQ8 and in the participant-level table. This should not break (nor populate) Phase 1 tables. Also check that the high/low target alignment columns in RQ8 are populated. This will need https://github.com/NextCenturyCorporation/itm-ingest/pull/82 to be run first.

### CODE REVIEW

**Review by phile-caci — APPROVED** [review]
LGTM!

**Comment by nextcen-dgemoets** [comment]
> Because definitions take a very long time to update. I will do it now, I suppose

If this should be a new ticket, no worries.  LMK if you prefer simply to write a ticket and I'll approve this one as-is.

**Comment by kaitlyn-sharo** [comment]
> > Because definitions take a very long time to update. I will do it now, I suppose
> 
> If this should be a new ticket, no worries. LMK if you prefer simply to write a ticket and I'll approve this one as-is.

already updated

**Review by nextcen-dgemoets — APPROVED** [review]

**Review by brianpippin — APPROVED** [review]
Everything is displaying for me.

**Pull request merged**
