### PR TITLE
Development to Main merge request.

### PR DESCRIPTION
**Pull request by brianpippin**

### CODE REVIEW

**Review by kaitlyn-sharo — COMMENTED** [review]
- Admin page on refresh returns to home page - not sure if this is expected behavior or not
- Extra column got added to text scenario results participant view somewhere along the way. All values show as NaN. It's the last column titled "alignmentData (s)". We could add alignment here (should take about 2 minutes) or take the column away
- Scenarios 9 and 10 have no data in Delegation Survey Results. Not sure if this is an issue

**Comment by brianpippin** [comment]
> * Admin page on refresh returns to home page - not sure if this is expected behavior or not
> * Extra column got added to text scenario results participant view somewhere along the way. All values show as NaN. It's the last column titled "alignmentData (s)". We could add alignment here (should take about 2 minutes) or take the column away
> * Scenarios 9 and 10 have no data in Delegation Survey Results. Not sure if this is an issue

Admin page on refresh to home page is desired, we don't want anyone being able to send someone directly to the admin page via url, so they need to go through all the proper channels.

If you think you can add alignment quickly feel free.  @dereknop can you check the scenarios 9 and 10 in the delegation survey, this could just be an artifact, verify if working as designed.

**Comment by dereknop** [comment]
> > * Admin page on refresh returns to home page - not sure if this is expected behavior or not
> > * Extra column got added to text scenario results participant view somewhere along the way. All values show as NaN. It's the last column titled "alignmentData (s)". We could add alignment here (should take about 2 minutes) or take the column away
> > * Scenarios 9 and 10 have no data in Delegation Survey Results. Not sure if this is an issue
> 
> Admin page on refresh to home page is desired, we don't want anyone being able to send someone directly to the admin page via url, so they need to go through all the proper channels.
> 
> If you think you can add alignment quickly feel free. @dereknop can you check the scenarios 9 and 10 in the delegation survey, this could just be an artifact, verify if working as designed.

Found the issue with scenario 9 and 10. Typo in json config. Writing python script to update mongo survey results to have proper scenario indexes for omnibus pages

**Comment by brianpippin** [comment]
> * Admin page on refresh returns to home page - not sure if this is expected behavior or not
> * Extra column got added to text scenario results participant view somewhere along the way. All values show as NaN. It's the last column titled "alignmentData (s)". We could add alignment here (should take about 2 minutes) or take the column away
> * Scenarios 9 and 10 have no data in Delegation Survey Results. Not sure if this is an issue

All issues have been discussed or correct, if @kaitlyn-sharo and @dereknop and or anyone else could give it another review.

**Review by kaitlyn-sharo — APPROVED** [review]

**Review by dereknop — APPROVED** [review]

**Pull request merged**
