### PR TITLE
Choose correct adms

### PR DESCRIPTION
**Pull request by kaitlyn-sharo**
https://nextcentury.atlassian.net/wiki/spaces/ITMC/pages/3213885465/Dry+Run+Evaluation+Delegation+Materials

Updated how adms are chosen based on link above. Please look over logic to ensure it looks correct. Also added a check to see if a pid has already been used

### CODE REVIEW

**Comment by nextcen-dgemoets** [comment]
The diffs are showing the more details modal changes.  I think development should be merged into here?

**Comment by dereknop** [comment]
> The diffs are showing the more details modal changes. I think development should be merged into here?



> The diffs are showing the more details modal changes. I think development should be merged into here?

I am going to push something to this branch. Hold off reviewing for now. I'll merge development in.

**Comment by dereknop** [comment]
Screenshot 2024-09-10 at 4 36 15 PM

Should get this screenshot if you try to take text-based scenarios with a PID that has already been used. If you've tested previous PR's, grab a PID from one of the documents in you `userScenarioResults` collection

**Comment by dereknop** [comment]
I didn't get a warning about a duplicate PID in the survey. I didn't get prompted with the post scenario measurements page (it appears to be the root cause, I'm looking into it).

**Review by dereknop — APPROVED** [review]

**Pull request merged**
