### PR TITLE
Itm 707 ph1 dropdowns

### PR DESCRIPTION
**Pull request by kaitlyn-sharo**
For this PR, please make sure that phase 1 drop downs appear (some may only appear once you've run probe matcher with eval 5 data - see the open pr) and that, when clicked, no errors occur. 

If you answer text surveys and delegation, those options should appear and the data should begin to autopopulate. 

All drop downs are:
RQ1
RQ2
RQ3
Exploratory
ADM Data
ADM Alignment Results
Home Page
Delegation Survey Results 
Text Scenario Results
Participant-Level Data
Human Sim Probe Data
Play-By-Play humans in sim

### CODE REVIEW

**Comment by phile-caci** [comment]
@kaitlyn-sharo ,
For http://localhost:3000/survey-results, should I be getting graphs here yet? There are also repeated Adept Scenario names in the Scenario list also, just making sure if that's ok.
image

**Review by nextcen-dgemoets — APPROVED** [review]
All phase 1 drop downs appeared on all of the pages mentioned by the PR.  No errors occurred.  Approved.

The rest of my comments and observations are not a request to fix, investigate, or prioritize over other work.  In many cases, they may be expected behavior based on the fact that much of our data is still test or placeholder data.  They could also be problems with my database.
- On the RQ and Home pages, the dropdowns default to Dry Run Evaluation and you have to change it to Phase 1 Evaluation.  Maybe it's an alphabetical thing, or maybe we still want DRE to be the default on prod because folks are still looking at that data a lot.  On other pages (mostly in the Human Evaluation Segments section), it does default (or stick) to Phase 1.
- On the Delegation Survey Results page, if the Survey Version were slightly longer, we wouldn't have to scroll.
  - Also, I got the same (possibly expected )behavior as Phi where there are no graphs and repeated Adept Scenario names in the Scenario list.
- On the ADM Alignment Results page, the DRE data is the same as the Phase 1 data.  I assume this is expected.

**Comment by kaitlyn-sharo** [comment]
> All phase 1 drop downs appeared on all of the pages mentioned by the PR. No errors occurred. Approved.
> 
> The rest of my comments and observations are not a request to fix, investigate, or prioritize over other work. In many cases, they may be expected behavior based on the fact that much of our data is still test or placeholder data. They could also be problems with my database.
> 
> * On the RQ and Home pages, the dropdowns default to Dry Run Evaluation and you have to change it to Phase 1 Evaluation.  Maybe it's an alphabetical thing, or maybe we still want DRE to be the default on prod because folks are still looking at that data a lot.  On other pages (mostly in the Human Evaluation Segments section), it does default (or stick) to Phase 1.
> * On the Delegation Survey Results page, if the Survey Version were slightly longer, we wouldn't have to scroll.
>   
>   * Also, I got the same (possibly expected )behavior as Phi where there are no graphs and repeated Adept Scenario names in the Scenario list.
> * On the ADM Alignment Results page, the DRE data is the same as the Phase 1 data.  I assume this is expected.

Yes, I did not change the defaults on several pages yet because we'll need the sim data first. We can do that next week, unless requested otherwise from the bosses! Super easy change eithe rway.

**Comment by kaitlyn-sharo** [comment]
> @kaitlyn-sharo , For http://localhost:3000/survey-results, should I be getting graphs here yet? There are also repeated Adept Scenario names in the Scenario list also, just making sure if that's ok. image

Great question, I'll take a look

**Comment by brianpippin** [comment]
Let's see all the defaults for Phase 1 now.  Also Phase 1 shouldn't be in the homepage drop down, although I think Phi has that configured on the Admin page.

**Review by brianpippin — APPROVED** [review]
Things looked good for me.

**Review by phile-caci — APPROVED** [review]
Thanks Kaitlyn, LGTM!

Drops down defaulted to PH1, except Home Page as expected
Survey Results look good.

**Pull request merged**
