### PR TITLE
font + styling improvements

### PR DESCRIPTION
**Pull request by dereknop**
Made font sizes bigger in delegation survey for medic actions, more consistent across Text-based scenarios and Survey. Click through some of the review pages a little bit and let me know if anything looks too small or unreadable

### CODE REVIEW

**Review by nextcen-dgemoets — APPROVED** [review]
Looks a lot better!  I no longer have to scale my browser text to 125% or so.

Unrelated to the ticket, when completing the text scenarios, if I use an existing PID and click OK, I get a stacktrace.  However, I didn't get this on prod, so, I guess not a problem?

```
Cannot read properties of undefined (reading 'Text-1')
TypeError: Cannot read properties of undefined (reading 'Text-1')
    at TextBasedScenariosPage.introSurveyComplete (http://localhost:3000/static/js/bundle.js:15837:62)
    at Event.fire (http://localhost:3000/static/js/bundle.js:414899:25)
    at SurveyModel.saveDataOnComplete (http://localhost:3000/static/js/bundle.js:446799:27)
    at SurveyModel.doComplete (http://localhost:3000/static/js/bundle.js:446761:16)
    at SurveyModel.doCurrentPageCompleteCore (http://localhost:3000/static/js/bundle.js:446394:25)
    at SurveyModel.doCurrentPageComplete (http://localhost:3000/static/js/bundle.js:446388:23)
    at SurveyModel.completeLastPage (http://localhost:3000/static/js/bundle.js:446320:26)
    at http://localhost:3000/static/js/bundle.js:448511:30
    at SurveyTaskManagerModel.waitAndExecute (http://localhost:3000/static/js/bundle.js:437861:13)
    at action (http://localhost:3000/static/js/bundle.js:448510:40)
ERROR
Cannot read properties of undefined (reading 'Text-1')
TypeError: Cannot read properties of undefined (reading 'Text-1')
    at TextBasedScenariosPage.introSurveyComplete (http://localhost:3000/static/js/bundle.js:15837:62)
    at Event.fire (http://localhost:3000/static/js/bundle.js:414899:25)
    at SurveyModel.saveDataOnComplete (http://localhost:3000/static/js/bundle.js:446799:27)
    at SurveyModel.doComplete (http://localhost:3000/static/js/bundle.js:446761:16)
    at SurveyModel.doCurrentPageCompleteCore (http://localhost:3000/static/js/bundle.js:446394:25)
    at SurveyModel.doCurrentPageComplete (http://localhost:3000/static/js/bundle.js:446388:23)
    at SurveyModel.completeLastPage (http://localhost:3000/static/js/bundle.js:446320:26)
    at http://localhost:3000/static/js/bundle.js:448511:30
    at SurveyTaskManagerModel.waitAndExecute (http://localhost:3000/static/js/bundle.js:437861:13)
    at action (http://localhost:3000/static/js/bundle.js:448510:40)
```

**Comment by dereknop** [comment]
> Unrelated to the ticket, when completing the text scenarios, if I use an existing PID and click OK, I get a stacktrace. However, I didn't get this on prod, so, I guess not a problem?
> 

I'll look into this, I probably did not properly account for this edge case.

**Review by brianpippin — APPROVED** [review]

**Review by phile-caci — APPROVED** [review]
LGTM, i tried an existing pid also, but didn't get an error...

**Comment by dereknop** [comment]
> LGTM, i tried an existing pid also, but didn't get an error...

Yea I couldn't recreate either. But will make a note of this

**Pull request merged**
