### PR TITLE
Research Question Pages/Tables

### PR DESCRIPTION
**Pull request by kaitlyn-sharo**
Added new header Data Analysis, with RQ1, RQ2, RQ3 dropdowns. RQ1 and RQ3 share the same graph. Most columns should be populated except the rating columns and the Alignment score (Delegator | Observed_ADM (target)) column. 

RQ2 has two graphs, though one cannot be created yet (hence the TODO). The other graph should be fully populated. 

To test, grab the latest S3 backup and run! Make sure all pages look good and that the graphs do not cause errors. Also make sure the download works.

Later, we will be adding the last graph, filters, variable definitions, and code from Ashu (you'll see two placeholder buttons that say "View R Syntax").

### CODE REVIEW

**Comment by dereknop** [comment]
I had cleared out my `surveyResults` and `userScenarioResults` to test something else I was working on, so I was able to see the design of the new pages and I think it looks very clean and easy to digest. 

I backed up using the 9/18 .dump file on AWS and now I am getting the following error on r1 and r3 pages. R2 works fine and looks great. 

Screenshot 2024-09-19 at 11 41 52 AM
Screenshot 2024-09-19 at 11 42 16 AM

Looks like line 142 of rq1-rq3.jsx

**Comment by kaitlyn-sharo** [comment]
> I backed up using the 9/18 .dump file on AWS and now I am getting the following error on r1 and r3 pages. R2 works fine and looks great.

> Looks like line 142 of rq1-rq3.jsx

Thanks for catching this! I was using a slightly older db version so that entry wasn't in mine. Turns out if they type in an "other" response it comes in as just a string, which can't be joined. This should be fixed now

**Review by dereknop — APPROVED** [review]
Works. I am going to approve this instead of accidentally merging lol

**Review by phile-caci — APPROVED** [review]
Looks good to me, everything works, except for the few things you mentioned that didn't work yet.

**Review by brianpippin — APPROVED** [review]
Looks good to me.  Let's get this merged and then a dev to main PR started!

**Pull request merged**
