### PR TITLE
Dev to Main

### PR DESCRIPTION
**Pull request by brianpippin**
Started dev to main because the remaining tickets could be deployed tomorrow or Monday if necessary.

### CODE REVIEW

**Review by phile-caci — APPROVED** [review]
test Dev UI with all the data ingest, clicked through most things, looks good to me

**Review by nextcen-dgemoets — APPROVED** [review]
Can't say I remember all of the changes since last time (though I did scan the commits), but I didn't see any problems clicking and scrolling around.

**Review by kaitlyn-sharo — COMMENTED** [review]
I'm having to refresh some of the RQ pages to get data to show up. Is anyone else seeing this? Just sometimes it says "showing 0 of x entries based on filters" but no filters have been chosen, then when I refresh it works. I hadn't seen this before

**Comment by nextcen-dgemoets** [comment]
> I'm having to refresh some of the RQ pages to get data to show up. Is anyone else seeing this? Just sometimes it says "showing 0 of x entries based on filters" but no filters have been chosen, then when I refresh it works. I hadn't seen this before

I didn't see that, at least on the pages I viewed.

**Comment by kaitlyn-sharo** [comment]
> I'm having to refresh some of the RQ pages to get data to show up. Is anyone else seeing this? Just sometimes it says "showing 0 of x entries based on filters" but no filters have been chosen, then when I refresh it works. I hadn't seen this before

I was experiencing this consistently and determined it was because I was missing formattedData in the useEffects dependency array. Probably things were loading in a different order than I expected, whether due to a slow computer or whatever. This has fixed the problem for me.

**Review by kaitlyn-sharo — APPROVED** [review]
I think all the data I added is showing up now and the survey change derek made that's in this works for me too

**Pull request merged**
