### PR TITLE
Itm 696

### PR DESCRIPTION
**Pull request by dereknop**
[Ticket](https://nextcentury.atlassian.net/jira/software/projects/ITM/boards/116?assignee=60ba425da547eb00686ee0ce&selectedIssue=ITM-696)

No ingest pr to run.

Use Kaitlyn's text scenario login to simulate a participant completing the scenarios ahead of time (u can get there from logging out and tabbing over) 
Screenshot 2024-11-13 at 5 30 16 PM

Click through the scenarios and then verify in your `userScenarioResults` collection that the following fields are attached to your documents. `kdmas`, `mostLeastAligned`, `alignmentData`, `serverSessionId` (if adept, should have `combinedSessionId` and `combinedAlignmentData` as well)

Also check that the documents are properly being marked as evalNumber: 5, and evalName: "Phase 1 Evaluation"

### CODE REVIEW

**Review by phile-caci — APPROVED** [review]
LGTM,

1. Logged in as a participant, and completed text scenario
2. Logged in as admin, and did a PID Lookup (202409121) on the email I used
3. Queried in mongo - `db.userScenarioResults.find({"participantID": "202409121"})`
4. Verified all keys had values (kdmas, mostLeastAligned, alignmentData, serverSessionId, combinedSessionId and combinedAlignmentData)
5. eval data existed
```
    evalNumber: 5,
    evalName: 'Phase 1 Evaluation',

```

**Comment by dereknop** [comment]
Note: after my latest commit the adept documents will no longer have an `alignmentData` or `combinedAlignmentData` field anymore, these were being populated using the old alignment endpoint `/api/v1/alignment/session`. They should still have `kdmas` and `mostLeastAligned`, which uses `/api/v1/get_ordered_alignment`. Soartech documents should remain unchanged.

**Comment by phile-caci** [comment]
> Note: after my latest commit the adept documents will no longer have an `alignmentData` or `combinedAlignmentData` field anymore, these were being populated using the old alignment endpoint `/api/v1/alignment/session`. They should still have `kdmas` and `mostLeastAligned`, which uses `/api/v1/get_ordered_alignment`. Soartech documents should remain unchanged.

Everything still looks good, ADEPT calls are being made to new endpoint:
image
ADEPT docs don't have `alignmentData` or `combinedAlignmentData`

**Comment by phile-caci** [comment]
PID Lookup changes looks good:

image


```
dashboard> db.participantLog.find({"ParticipantID": 202409103})
[
  {
...
    ParticipantID: 202409103,
    'Text-1': 'AD-2',
    'Text-2': 'ST-2',
    'Sim-1': 'AD-3',
    'Sim-2': 'ST-3',
...
  }
]

```

Lookup:
```
    'AD-3': ['Eval-Adept_Desert'],
    'ST-3': ['stq4_ph1', 'stv4_ph1'],
```

**Review by nextcen-dgemoets — APPROVED** [review]
LGTM,

- Logged in as a participant, and completed text scenario
- Logged in as admin, and did a PID Lookup (20249217) on the email I used
- Queried in mongo - db.userScenarioResults.find({"participantID": "20249217"})
- Verified all keys had values (kdmas, mostLeastAligned, alignmentData (ST), serverSessionId (ST), and combinedSessionId (ADEPT)
- All records were properly marked as evalNumber: 5, and evalName: "Phase 1 Evaluation"
- PID Lookup showed `PID`, `SIM-1`, and `SIM-2`.
- There was no extraneous console logging.  ;-)

Only question:  it looks like ADEPT has `combinedSessionId` and ST has `serverSessionId` but the instructions suggest that ADEPT should have `serverSessionId` as well.  I assume `serverSessionId` is ST only?

**Comment by dereknop** [comment]
> Only question: it looks like ADEPT has `combinedSessionId` and ST has `serverSessionId` but the instructions suggest that ADEPT should have `serverSessionId` as well. I assume `serverSessionId` is ST only?

I should have noted that in my earlier comment. We are running a combined session for the three ADEPT scenarios but the SoarTech ones are standalone. I removed the individual sessions from the ADEPT scenarios when I removed the calls to `/api/v1/alignment/session`

**Review by kaitlyn-sharo — APPROVED** [review]
It all looks great to me!

**Pull request merged**
