### PR TITLE
Dev to Main

### PR DESCRIPTION
**Pull request by brianpippin**

### CODE REVIEW

**Comment by nextcen-dgemoets** [comment]
I'm getting a crash on RQ2 page:
rq2

**Comment by dereknop** [comment]
> I'm getting a crash on RQ2 page: 
Looks like this is coming from an incomplete document. I'll throw in a check for if the doc has the mostLeastAligned array before it tries to iterate.

**Comment by nextcen-dgemoets** [comment]
I was filling out a delegation survey (standard through the menu, not from online), then brought up the RQ2 page (then tried again with Home) and it didn't prompt me.

**Comment by brianpippin** [comment]
> I was filling out a delegation survey (standard through the menu, not from online), then brought up the RQ2 page (then tried again with Home) and it didn't prompt me.

It looks like this block was removed for shouldBlockNavigation but nothing replaced it.

**Comment by dereknop** [comment]
working on fix

**Comment by dereknop** [comment]
give it a shot now. Things that should be blocked:

- navigating using the nav bar
- browser refresh
- browser back button
- tab close (now window)

**Comment by brianpippin** [comment]
The Delegation Survey and navigating away seems to be fixed for me now, I can't approve my own code review but so far no other issues from me.

**Review by dereknop — APPROVED** [review]

**Review by kaitlyn-sharo — APPROVED** [review]
Tested the survey both ways, got warnings before going back, got the expected scenarios.

**Comment by dereknop** [comment]
>I can't approve my own code review 

2i8vxe

**Comment by nextcen-dgemoets** [comment]
FWIW, I didn't encounter any issues either.  I had an old incomplete survey that I was able to use the Copy Link feature to continue.  And my adept user can see the adept content in the progress table.  No back button problems.

**Pull request merged**
