### PR TITLE
ensure online delegation scenarios are being grabbed correctly from plog

### PR DESCRIPTION
**Pull request by kaitlyn-sharo**
Please check the scenarios you get for delegation against the database when going through the online-only portion. Ensure everything still works, including the startSurvey special link that skips straight to the survey.

### CODE REVIEW

**Review by dereknop — APPROVED** [review]
I used this link: 
http://localhost:3000/remote-text-survey?adeptQualtrix=true&PROLIFIC_PID=12345&ContactID=Bobby

Generated this to participant log:
Screenshot 2024-12-12 at 12 54 47 PM

I saw the following text scenarios:
MJ5, MJ1, IO1, QOL4, and VOL4

That would be expected behavior based on the participant log.

The delegation survey (tested letting myself get redirected from text based scenarios as well as using link in progress table) gave me the expected scenarios based on participant log entry:
Screenshot 2024-12-12 at 1 00 20 PM

**Review by nextcen-dgemoets — APPROVED** [review]
I used this link:
http://localhost:3000/remote-text-survey?adeptQualtrix=true&PROLIFIC_PID=54321&ContactID=Joey&pid=202411512&class=Online

Generated this to participant log:
pr197

I saw the following text scenarios:
- IO1, MJ1, MJ2, QOL2, VOL2
...which the magic 8-ball says is correct.

The delegation survey (tested letting myself get redirected from text based scenarios as well as using link in progress table) gave me the following scenarios:
- DryRunEval-MJ5-eval, qol-ph1-eval-4, DryRunEval-IO5-eval, vol-ph1-eval-4
...which the magic 8-ball says is also correct.

**Review by phile-caci — APPROVED** [review]
LGTM, went through 2 sets, they look good according to the mappins

```
    'Text-1': 'ST-3', <- Got qol-ph1-eval-4, vol-ph1-eval-4
    'Text-2': 'AD-1', < - Got phase1-adept-eval-MJ2, phase1-adept-train-MJ1, phase1-adept-train-IO1
    'Sim-1': 'ST-1',
    'Sim-2': 'AD-2',
    'Del-1': 'ST-2',
    'Del-2': 'AD-3',
    ADMOrder: 4,
    ParticipantID: 202411547,
```

For text:
```
dashboard> db.userScenarioResults.find({"participantID": "202411547"}, {"scenario_id":1})
    scenario_id: 'qol-ph1-eval-4'
    scenario_id: 'vol-ph1-eval-4'
    scenario_id: 'phase1-adept-eval-MJ2'
    scenario_id: 'phase1-adept-train-MJ1'
    scenario_id: 'phase1-adept-train-IO1'
```

For Survey:
```
        scenarioIndex: 'vol-ph1-eval-3',
        scenarioIndex: 'qol-ph1-eval-3',
        scenarioIndex: 'DryRunEval-IO5-eval',
        scenarioIndex: 'DryRunEval-MJ5-eval',

```

NEXT TEST:

```
    'Text-1': 'AD-1',
    'Text-2': 'ST-1',
    'Sim-1': 'AD-2',
    'Sim-2': 'ST-2',
    'Del-1': 'AD-3',
    'Del-2': 'ST-3',
    ADMOrder: 3,
    ParticipantID: 202411548,
```

Text:
```
dashboard> db.userScenarioResults.find({"participantID": "202411548"}, {"scenario_id":1})
...
    scenario_id: 'phase1-adept-eval-MJ2'
    scenario_id: 'phase1-adept-train-MJ1'
    scenario_id: 'phase1-adept-train-IO1'
    scenario_id: 'qol-ph1-eval-2'
    scenario_id: 'vol-ph1-eval-2'
...
```

Survey
```
# mongosh mongodb://localhost:27030/dashboard -u dashroot -p dashr00tp@ssw0rd --authenticationDatabase admin --eval "db.surveyResults.find({\"results.pid\": \"202411548\"})" | grep scenarioIndex

        scenarioIndex: 'DryRunEval-MJ5-eval',
        scenarioIndex: 'qol-ph1-eval-4',
        scenarioIndex: 'DryRunEval-IO5-eval',
        scenarioIndex: 'vol-ph1-eval-4',

```

Mappings:

TEXT

'AD-1': ['phase1-adept-eval-MJ2', 'phase1-adept-train-MJ1', 'phase1-adept-train-IO1'],
'AD-2': ['phase1-adept-eval-MJ4', 'phase1-adept-train-MJ1', 'phase1-adept-train-IO1'],
'AD-3': ['phase1-adept-eval-MJ5', 'phase1-adept-train-MJ1', 'phase1-adept-train-IO1'],
'ST-1': ['qol-ph1-eval-2', 'vol-ph1-eval-2'],
'ST-2': ['qol-ph1-eval-3', 'vol-ph1-eval-3'],
'ST-3': ['qol-ph1-eval-4', 'vol-ph1-eval-4'],

SURVEY
"AD-1": ["DryRunEval-MJ2-eval", "DryRunEval-IO2-eval"],
"AD-2": ["DryRunEval-MJ4-eval", "DryRunEval-IO4-eval"],
"AD-3": ["DryRunEval-MJ5-eval", "DryRunEval-IO5-eval"],
"ST-1": ["qol-ph1-eval-2", "vol-ph1-eval-2"],
"ST-2": ["qol-ph1-eval-3", "vol-ph1-eval-3"],
"ST-3": ["qol-ph1-eval-4", "vol-ph1-eval-4"],

**Comment by joshuale-caci** [comment]
image

This is my participant data and I was able access the survey through the progress table which was nice.

My runs were
image

IO1, MJ1, MJ5, QOL3, VOL3

**Review by joshuale-caci — APPROVED** [review]
image

This is my participant data and I was able access the survey through the progress table which was nice.

My runs were
image

IO1, MJ1, MJ5, QOL3, VOL3

**Comment by nextcen-dgemoets** [comment]
Er, one quick thing-- when does the Copy Link button disappear?  I'm still seeing it for my 202411512 patient after I Refresh Data or refresh the browser.

**Comment by nextcen-dgemoets** [comment]
> Er, one quick thing-- when does the Copy Link button disappear? I'm still seeing it for my 202411512 patient after I Refresh Data or refresh the browser.

Hmm, it may be because I copied the the link while I was still working on the delegation scenario.  Then after I finished it, I pasted the link, so maybe it thinks I'm still working on it.  I think it's fine, but maybe I'll double-check during dev-to-main.

**Pull request merged**
