### PR TITLE
Itm 639 dre home

### PR DESCRIPTION
**Pull request by kaitlyn-sharo**
Added the DRE home page (and made it default). Separated the MRE home page from programQuestions, did some additional cleanup. 

Check that:
1. MRE home page still works
2. DRE home page loads as default
3. DRE graphs look like quick look graphs

The home page is missing a few graphs (you'll see these commented out) due to:
1. (RQ3 line graphs) Inability to calculate logistic mixed regression in javascript and 
2. (RQ1) Box and whisker plots matching data in the tables, but not matching the quick look report

### CODE REVIEW

**Review by dereknop — APPROVED** [review]
Worked for me. Shared minor feedback via teams

**Review by phile-caci — COMMENTED** [review]
MRE home page still works - Still works!
DRE home page loads as default - DRE home page loads by default!
DRE graphs look like quick look graphs - Compared to Quicklook report from 10/16... 

This graph looked off,`Parallax ADMs Alignment by Target on Quality of Life` :
(but maybe the last few targets are ordered differently?)
From UI:
image

From Report:
image

**Comment by kaitlyn-sharo** [comment]
> MRE home page still works - Still works! DRE home page loads as default - DRE home page loads by default! DRE graphs look like quick look graphs - Compared to Quicklook report from 10/16...
> 
> This graph looked off,`Parallax ADMs Alignment by Target on Quality of Life` : (but maybe the last few targets are ordered differently?) From UI: image
> 
> From Report: image

Yes, I'd agree it looks off at the end, but I do think it's just a slightly different order. If you look at the values, they seem to be swapped

**Review by phile-caci — APPROVED** [review]
LGTM!

**Comment by kaitlyn-sharo** [comment]
> Worked for me. Shared minor feedback via teams

Added responsive styling for the fun scatter plots. Now everything styles pretty well in different modes (mobile, tablet, laptop). Some of the super-wide graphs are a little too big for mobile, but there isn't weird overflow like there was on the scatters

**Review by nextcen-dgemoets — APPROVED** [review]
I didn't see any problems, but obviously Jennifer and/or Brian should sign off on this.

**Comment by brianpippin** [comment]
Kaitlyn ran all the charts by us before posting the PR.

**Pull request merged**
