### PR TITLE
Itm 585 update results page for dre

### PR DESCRIPTION
**Pull request by phile-caci**
1. Survey Results is working, Kaitlyn fixed survey results comparison charts (Thanks!)

### CODE REVIEW

**Comment by phile-caci** [comment]
Hey @dereknop , I got the Survey Results Page working.. but for TextBasedResultsPage there's a lot going on. Are you able to look at this? I don't mind banging my head on it some more if you're busy.

**Comment by brianpippin** [comment]
Screenshot 2024-09-18 at 9 00 16 AM
This looks close but we are still missing the graphs for the comparison of the medics?  I will take a peek but I bet @kaitlyn-sharo or @dereknop might know quicker what is amiss

**Comment by phile-caci** [comment]
> Screenshot 2024-09-18 at 9 00 16 AM This looks close but we are still missing the graphs for the comparison of the medics? I will take a peek but I bet @kaitlyn-sharo or @dereknop might know quicker what is amiss

checking it out now, I thought I had comparisons working

**Comment by phile-caci** [comment]
Should I hold off from making any updates to the comparison charts for DryRun?  Sounds like these charts might be getting a rework?

**Comment by brianpippin** [comment]
> Should I hold off from making any updates to the comparison charts for DryRun? Sounds like these charts might be getting a rework?

I don't know that these charts are getting reworked as much as we are adding new data tables.

**Review by kaitlyn-sharo — COMMENTED** [review]
I'm still not seeing comparisons, even after the changes. Are they working locally? Am I maybe missing a step?

**Comment by phile-caci** [comment]
> I'm still not seeing comparisons, even after the changes. Are they working locally? Am I maybe missing a step?

Sry, still working on the comparisons

**Review by brianpippin — APPROVED** [review]
I can see the comparison views now!  LGTM

**Review by nextcen-dgemoets — COMMENTED** [review]
Overall, things look pretty good, other than that the data is sparse so far which makes the graphs less interesting than they will be.

A few thoughts:
- Maybe this is just one of those quirks we can't do anything about, but can we make the graphs non-interactable?  It seems to want to do some kind of zooming thing when I click/drag, and the result always looks bad.  And clicking on a bar seems to make some of the data disappear??
- Can we make the scenario selector list longer/taller?  At 100% zoom, it perfectly fits the four choices for Survey 3.x, but for 4.x, combined with the long/wrapping scenario names/labels, the list accommodates 2 1/2 entries.
- When I download the v4 survey data, PID 20249214 has two entries, one of which is incomplete.  Also, maybe we should sort the table (display and download version) by PID?  It seems almost sorted.

**Comment by nextcen-dgemoets** [comment]
One more thing-- by default in the Tabulated Survey Results pop-up, can we make survey version 4 on and everything else off?  Right now, 2 is on and everything else is off, and even if you change it, it doesn't stick.

**Comment by brianpippin** [comment]
> One more thing-- by default in the Tabulated Survey Results pop-up, can we make survey version 4 on and everything else off? Right now, 2 is on and everything else is off, and even if you change it, it doesn't stick.

That is already done in another ticket.  @dereknop completed that.

**Comment by kaitlyn-sharo** [comment]
> Overall, things look pretty good, other than that the data is sparse so far which makes the graphs less interesting than they will be.
> 
> A few thoughts:
> 
> * Maybe this is just one of those quirks we can't do anything about, but can we make the graphs non-interactable?  It seems to want to do some kind of zooming thing when I click/drag, and the result always looks bad.  And clicking on a bar seems to make some of the data disappear??
> * Can we make the scenario selector list longer/taller?  At 100% zoom, it perfectly fits the four choices for Survey 3.x, but for 4.x, combined with the long/wrapping scenario names/labels, the list accommodates 2 1/2 entries.
> * When I download the v4 survey data, PID 20249214 has two entries, one of which is incomplete.  Also, maybe we should sort the table (display and download version) by PID?  It seems almost sorted.

We (Derek and I) have tried to make these graphs non-interactable, but there's something quirky about them that doesn't let us. We never figured it out but we both spent a significant amount of time looking into it and being unfruitful in our efforts. 

Do you have something you want us to do about the 20249214 data? Or was that just a comment to note? All that means is the survey was started with that participant ID twice, but only finished once. 

I will work on the sorting and making the scenario selector list taller

**Comment by brianpippin** [comment]
> > Overall, things look pretty good, other than that the data is sparse so far which makes the graphs less interesting than they will be.
> > A few thoughts:
> > 
> > * Maybe this is just one of those quirks we can't do anything about, but can we make the graphs non-interactable?  It seems to want to do some kind of zooming thing when I click/drag, and the result always looks bad.  And clicking on a bar seems to make some of the data disappear??
> > * Can we make the scenario selector list longer/taller?  At 100% zoom, it perfectly fits the four choices for Survey 3.x, but for 4.x, combined with the long/wrapping scenario names/labels, the list accommodates 2 1/2 entries.
> > * When I download the v4 survey data, PID 20249214 has two entries, one of which is incomplete.  Also, maybe we should sort the table (display and download version) by PID?  It seems almost sorted.
> 
> We (Derek and I) have tried to make these graphs non-interactable, but there's something quirky about them that doesn't let us. We never figured it out but we both spent a significant amount of time looking into it and being unfruitful in our efforts.
> 
> Do you have something you want us to do about the 20249214 data? Or was that just a comment to note? All that means is the survey was started with that participant ID twice, but only finished once.
> 
> I will work on the sorting and making the scenario selector list taller

Not too worried about the tables, that only happens if you try to zoom and I am able to reset them, so let's leave those as is.  As for the duplicate data, let's wait for Jennifer before we "clean" any data, and for now that should stay as is.

**Comment by nextcen-dgemoets** [comment]
> We (Derek and I) have tried to make these graphs non-interactable, but there's something quirky about them that doesn't let us. We never figured it out but we both spent a significant amount of time looking into it and being unfruitful in our efforts.
> 
> Do you have something you want us to do about the 20249214 data? Or was that just a comment to note? All that means is the survey was started with that participant ID twice, but only finished once.
> 
> I will work on the sorting and making the scenario selector list taller

Yeah, I figured that might be the case with the graphs.
For data things, I just point them out and let somebody else decide if they're a problem, if they need to be deleted/scrubbed, etc.

**Review by nextcen-dgemoets — APPROVED** [review]
The minor UI things have been resolved.
We'll leave the extra data there unless/until Jennifer says otherwise.

**Pull request merged**
