### PR TITLE
Graphql Hardening

### PR DESCRIPTION
**Pull request by brianpippin**
Check that you can get to all pages and that set functionality still works and make sure everything stays intact.

### CODE REVIEW

**Review by kaitlyn-sharo — APPROVED** [review]
I was able to access everything normally

**Review by jaudick — APPROVED** [review]

**Comment by phile-caci** [comment]
sry give me a few more minutes on this.. testing the prod setup locally to make sure the graphql playground isn't exposed

**Review by joshuale-caci — APPROVED** [review]
Checked all the pages and they look like they are functioning normal to me.

**Review by phile-caci — APPROVED** [review]
@brianpippin , sry, took me a moment to get NGINX running locally, 

I can still get to the graphql sandbox, it looks like we need one more setting:

in "docker_setup/docker-compose.yml"
NODE_ENV: "production"

I made that changed and committed it.   Tested locally and blocks the sandbox now.

**Comment by brianpippin** [comment]
> @brianpippin , sry, took me a moment to get NGINX running locally,
> 
> I can still get to the graphql sandbox, it looks like we need one more setting:
> 
> in "docker_setup/docker-compose.yml" NODE_ENV: "production"
> 
> I made that changed and committed it. Tested locally and blocks the sandbox now.

I tested as well, no issues.  Thanks Phi!

**Pull request merged**
