### PR TITLE
ITM 459 Add additional Eval drop downs

### PR DESCRIPTION
**Pull request by phile-caci**
Added evalName/evalNumber to `surveyResults` and `userScenarioResults` to support for the drop downs.

Will need to add eval fields to your local mongo for testing:
```
db.surveyResults.updateMany({}, { $set: { "evalNumber": 3 } }) 
db.surveyResults.updateMany({}, { $set: { "evalName": "Metrics Evaluation" } }) 
db.userScenarioResults.updateMany({}, { $set: { "evalNumber": 3 } }) 
db.userScenarioResults.updateMany({}, { $set: { "evalName": "Metrics Evaluation" } }) 
```

Added a table for EvaluationIDS
```
db.createCollection("evaluationIDS")  
db.evaluationIDS.insertOne({  
  "evalNumber": 1,  
  "evalName": "MVP",  
  "showMainPage": false})  
db.evaluationIDS.insertOne({  
  "evalNumber": 2,  
  "evalName": "September Milestone",  
  "showMainPage": false})  
db.evaluationIDS.insertOne({  
  "evalNumber": 3,  
  "evalName": "Metrics Evaluation",  
  "showMainPage": true})  
db.evaluationIDS.insertOne({  
  "evalNumber": 4,  
  "evalName": "Dry Run Evaluation",  
  "showMainPage": false})  
db.evaluationIDS.find() 

```

Added drop downs to:
1. Program Questions: http://localhost:3000/
2. Text Based Results: http://localhost:3000/text-based-results
3. Human Participant Data: Within-Subjects Analysis: http://localhost:3000/humanSimParticipant
4. Human Simulator Probe by Environment: http://localhost:3000/humanProbeData
5. Play-by-play: Humans In Sim: http://localhost:3000/human-results

Another Note: Querying the programQuestions page by eval took it down from 90mb to 11mb... that should be much faster now as well.

### CODE REVIEW

**Comment by phile-caci** [comment]
> The ticket lists three other places it's needed:
> 
> * http://localhost:3000/text-based-results
> * http://localhost:3000/humanSimParticipant
> * http://localhost:3000/humanProbeData

I didn't see any evalName/evalNumber in those collections.  LMK if I should add them, and if so, what they should be...

These are what I currently see in other collections:
                  "evalNumber": 1,
                  "evalName": "MVP"
                  "evalNumber": 2,
                  "evalName": "September Milestone"
                  "evalNumber": 3,
                  "evalName": "Metrics Evaluation"

**Comment by nextcen-dgemoets** [comment]
> I didn't see any evalName/evalNumber in those collections. LMK if I should add them, and if so, what they should be...

I'm only reporting what's in the ticket, which I didn't write.  Maybe ask @brianpippin or @dereknop for their thoughts.

**Comment by brianpippin** [comment]
I have to write up a bunch of additional stuff I was thinking for this ticket.  I'll add to the ticket and here this morning.

**Comment by brianpippin** [comment]
Screenshot 2024-08-16 at 9 06 21 AM

So we should have something like this for only Metrics Evaluation currently but Dry Run Evaluation so evalNumber >= 3

On the following pages:
Play by Play: Human, Human Sim Probe Values, Human Participant Data: Within Subject, and the Home Page

There should be something similar to the page "ADM Data" for picking the Evaluation on the "Text Scenario Results" page.

This will make sure we are ready and auto populating for the Dry Run Evaluation these metrics pages.

**Comment by phile-caci** [comment]
> Screenshot 2024-08-16 at 9 06 21 AM
> 
> So we should have something like this for only Metrics Evaluation currently but Dry Run Evaluation so evalNumber >= 3
> 
> On the following pages: Play by Play: Human, Human Sim Probe Values, Human Participant Data: Within Subject, and the Home Page
> 
> There should be something similar to the page "ADM Data" for picking the Evaluation on the "Text Scenario Results" page.
> 
> This will make sure we are ready and auto populating for the Dry Run Evaluation these metrics pages.

Sounds good, there's no, evalName/evalNumber in those collections now, I can add it.

It'll probably need to be added in at the source of the data as well, want me to do that as a part of this ticket or create a new one for that.

**Comment by brianpippin** [comment]
> > Screenshot 2024-08-16 at 9 06 21 AM
> > So we should have something like this for only Metrics Evaluation currently but Dry Run Evaluation so evalNumber >= 3
> > On the following pages: Play by Play: Human, Human Sim Probe Values, Human Participant Data: Within Subject, and the Home Page
> > There should be something similar to the page "ADM Data" for picking the Evaluation on the "Text Scenario Results" page.
> > This will make sure we are ready and auto populating for the Dry Run Evaluation these metrics pages.
> 
> Sounds good, there's no, evalName/evalNumber in those collections now, I can add it.
> 
> It'll probably need to be added in at the source of the data as well, want me to do that as a part of this ticket or create a new one for that.

It can be part of this ticket as that was the spirit of this ticket, but if we need to make sure there is a ticket to add it to the future ingest items, we can do that as well.

**Comment by phile-caci** [comment]
@brianpippin , this should be ready for review.. I added evalName/evalNumber to `surveyResults` and `userScenarioResults` to support for the drop downs.

I wasn't sure if we should do this in itm-ingest since it was a one-time/point-in-time update?

Added drop downs to:

1. Program Questions: http://localhost:3000/
2. Text Based Results: http://localhost:3000/text-based-results
3. Human Participant Data: Within-Subjects Analysis: http://localhost:3000/humanSimParticipant
4. Human Simulator Probe by Environment: http://localhost:3000/humanProbeData
5. Play-by-play: Humans In Sim: http://localhost:3000/human-results

Add to your local mongo:
```
db.surveyResults.updateMany({}, { $set: { "evalNumber": 3 } }) 
db.surveyResults.updateMany({}, { $set: { "evalName": "Metrics Evaluation" } }) 
db.userScenarioResults.updateMany({}, { $set: { "evalNumber": 3 } }) 
db.userScenarioResults.updateMany({}, { $set: { "evalName": "Metrics Evaluation" } }) 
```

**Comment by phile-caci** [comment]
Added an admin panel to control which evaluations can be seleted on the homepage(programQuestions). Should be ready for review.

**Comment by phile-caci** [comment]
> db.surveyResults.updateMany({}, { $set: { "evalNumber": 3 } }) 
> db.surveyResults.updateMany({}, { $set: { "evalName": "Metrics Evaluation" } }) 
> db.userScenarioResults.updateMany({}, { $set: { "evalNumber": 3 } }) 
> db.userScenarioResults.updateMany({}, { $set: { "evalName": "Metrics Evaluation" } })

Thanks Brian!
Added a corresponding itm-ingest ticket [itm-ingest](https://github.com/NextCenturyCorporation/itm-ingest/pull/28)

**Review by brianpippin — APPROVED** [review]

**Pull request merged**
