### PR TITLE
Dev to Main

### PR DESCRIPTION
**Pull request by brianpippin**
Starting this PR for the deployment

### CODE REVIEW

**Review by dereknop — APPROVED** [review]
https://darpaitm.caci.com/remote-text-survey?adeptQualtrix=true&PROLIFIC_PID=123&ContactID=Bob&pid=202411513&class=Online&startSurvey=true

I used this url to start taking text based scenarios. After getting through them, my data was populated in the progress table with my prolific pid and contact id. I was able to close the tab open that was already on the survey and use the link from the progress table to finish the survey. I checked that there was no problem with 'm'. At the end of the survey I got redirected with the correct information still present:

Screenshot 2024-12-10 at 6 49 37 PM

**Review by phile-caci — APPROVED** [review]
Ran through an Adept online twice, Survey had no issues with M or other key presses, Adept User permission worked as expected, COntactID and Prolific PID was on Progress tables, Survey link looked as expected.

**Comment by nextcen-dgemoets** [comment]
I was occasionally able to use the back button without getting the pop-up.  I haven't yet detected a pattern of when I get the pop-up and when I don't.  There were all when using the adept online link entry to the system.

**Comment by nextcen-dgemoets** [comment]
Other than the back button issue noted above (only on text scenarios), I didn't encounter any issues and tested the new functionality.

**Pull request merged**
