### PR TITLE
Phase 1 Delegation Survey

### PR DESCRIPTION
**Pull request by kaitlyn-sharo**
Two tasks are included in this one:
1. Delegation survey is set up for phase 1 - review page now has ph1 and dre surveys, like the text scenarios review page. You will need to run the ingest script first
2. Road-not-taken is set up to show all the options the medic had when they chose their action. This only applies to soartech scenarios. 

The "Take Delegation Survey" page is NOT ready for review yet. That will be in our next PR.

### CODE REVIEW

**Comment by dereknop** [comment]
It is probably against the rules for me to approve this. Everything looks good as far as I can see

**Comment by brianpippin** [comment]
> It is probably against the rules for me to approve this. Everything looks good as far as I can see

You can still approve it, we should probably just make sure to get 3 approvals if one of them is yours since you worked on it as well :)

**Review by dereknop — APPROVED** [review]
boom 🫳🏻🎤

**Comment by nextcen-dgemoets** [comment]
Okay, I finally found a repeatable one:
- `phase1-adept-eval-MJ2`
- `ALIGN-ADM-OutlinesBaseline`
- `ADEPT-DryRun-Moral judgement-0.2`

**Comment by kaitlyn-sharo** [comment]
> I'm not sure, but I think there's a minor UI issue where when you select your configuration from the list(s), it doesn't start at the top of the actual review page, and instead starts you mid-page somewhere. If you pick one of the early configs (no scrolling), it goes to the top of the page, but if you scroll down (e.g., one of the DRE scenarios), you will not start at the top of the page and need to scroll up.

Not going to fix this right now. We are happy to do it if you make it a ticket for some other time, but we have higher-priority items than this currently

**Comment by nextcen-dgemoets** [comment]
> Not going to fix this right now. We are happy to do it if you make it a ticket for some other time, but we have higher-priority items than this currently

Obviously there are higher-priority items.  Derek said he'd add a scroll to top when we have the survey up.

**Review by nextcen-dgemoets — APPROVED** [review]

**Review by brianpippin — APPROVED** [review]

**Review by phile-caci — APPROVED** [review]
Quick spot check, LGTM!

**Pull request merged**
