### PR TITLE
Itm 630 open world

### PR DESCRIPTION
**Pull request by kaitlyn-sharo**
Run the ingest branch first.

Added open world analysis to RQ8. Check to make sure data seems reasonable, maybe even spot-check by hand against a csv. 

Includes a few other minor file changes due to open world data being included in the database now. That data needs to be excluded from some other pages. Please check around the other pages to make sure there are no errors.

### CODE REVIEW

**Comment by phile-caci** [comment]
@kaitlyn-sharo , this is right: After the `Alignment Score` column, all the data is the same across the participant id/Attribute.
Or did I mess up somewhere?

image

**Comment by kaitlyn-sharo** [comment]
> @kaitlyn-sharo , this is right: After the `Alignment Score` column, all the data is the same across the participant id/Attribute. Or did I mess up somewhere?
> 
> image

Yes, that's correct. There was only one open world scene, but 4 attributes for text scenarios. So we have one row per text scenario attribute, but it all maps to the same open world scene

**Review by phile-caci — APPROVED** [review]
LGTM,

Spot checked with 5c6b5a2d-7595-4fde-bb0c-db453d1c8ea8_202409101.csv

Counted treatment total of 20 (22 -2 for Pulse Oximeter ) across 8 unique patients for an avg of 2.5, as shown on the dashboard

Counted TAG_APPLIED, looked only at the last tag for correctness and counting only unique patients, 6 correct / 8 unique patents = .75 accuracy, just like the dashboard.

```
TAG_APPLIED,106900,9/24/2024 11:42:06 AM,5c6b5a2d-7595-4fde-bb0c-db453d1c8ea8,2.0,,,,,,,,,,,,,,,US Soldier 1,,,,,,,,,,,,,,red,
TAG_APPLIED,119620,9/24/2024 11:42:18 AM,5c6b5a2d-7595-4fde-bb0c-db453d1c8ea8,2.0,,,,,,,,,,,,,,,US Soldier 3,,,,,,,,,,,,,,gray,
TAG_APPLIED,143034,9/24/2024 11:42:42 AM,5c6b5a2d-7595-4fde-bb0c-db453d1c8ea8,2.0,,,,,,,,,,,,,,,**US Soldier 2,,,,,,,,,,,,,,yellow_orange,**
TAG_APPLIED,148735,9/24/2024 11:42:47 AM,5c6b5a2d-7595-4fde-bb0c-db453d1c8ea8,2.0,,,,,,,,,,,,,,,US Soldier 2,,,,,,,,,,,,,,red,
TAG_APPLIED,173673,9/24/2024 11:43:12 AM,5c6b5a2d-7595-4fde-bb0c-db453d1c8ea8,2.0,,,,,,,,,,,,,,**,Civilian 1,,,,,,,,,,,,,,yellow_orange,**
TAG_APPLIED,242545,9/24/2024 11:44:21 AM,5c6b5a2d-7595-4fde-bb0c-db453d1c8ea8,2.0,,,,,,,,,,,,,,,Civilian 2,,,,,,,,,,,,,,red,
TAG_APPLIED,254798,9/24/2024 11:44:33 AM,5c6b5a2d-7595-4fde-bb0c-db453d1c8ea8,2.0,,,,,,,,,,,,,,,**US Soldier 4,,,,,,,,,,,,,,green_blue,**
TAG_APPLIED,298500,9/24/2024 11:45:17 AM,5c6b5a2d-7595-4fde-bb0c-db453d1c8ea8,2.0,,,,,,,,,,,,,,,Attacker 1,,,,,,,,,,,,,,red,
TAG_APPLIED,350540,9/24/2024 11:46:09 AM,5c6b5a2d-7595-4fde-bb0c-db453d1c8ea8,2.0,,,,,,,,,,,,,,,**Attacker 2,,,,,,,,,,,,,,green_blue,**
TAG_APPLIED,412515,9/24/2024 11:47:11 AM,5c6b5a2d-7595-4fde-bb0c-db453d1c8ea8,2.0,,,,,,,,,,,,,,,Civilian 1,,,,,,,,,,,,,,red,

```

**Review by nextcen-dgemoets — APPROVED** [review]
LGTM,

Spot checked with 3b9aca2d-cc33-4799-af3a-18c2a7e1e17e_202409120.csv

Counted `TOOL_APPLIED` total of 23 (minus 9 Pulse Oximeter) equals 14 treatments (as shown on the dashboard), across 8 unique patients for an avg of 1.75, as shown on the dashboard.

Counted `TAG_APPLIED`, looked only at the last tag for correctness and counting only unique patients, 5 correct / 8 unique patents = .625 accuracy, as shown on the dashboard.

My only other comment-- which does not pertain to work performed as part of this PR-- is that the RQ8 table, there is a column labelled "Participant KDMA", but in the Variable Definitions it's listed as "Delegator KDMA".

**Pull request merged**
