### PR TITLE
Session ids

### PR DESCRIPTION
**Pull request by kaitlyn-sharo**
The server session ids used to get alignment for text scenarios have been added to the RQ1-3 graph.

The server session ids used by the adms to get alignment have been added to the RQ 22-23 graph.

The server session ids used to get alignment for the sim have been added to the human sim probe graphs. You will need to run the latest probe matcher with RUN_ALIGNMENT=True to see these values. 

Must run docker script due to a minor change in one of the queries

### CODE REVIEW

**Comment by nextcen-dgemoets** [comment]
This might have already been there and I didn't notice it (in other words, not part of this ticket), but in RQ1 Data's chart, the "Delegation preference" columns (both A/B and A/M) have some values of y and n.  Maybe this has to do with the Note in the definition:  "Note: response backfilled to ADMs in the same block to aid in calculation of chosen or not chosen RQ3.2"  But it's a little weird to see y and n when you're expecting A and B.  I imagine there's nothing to be done.

**Comment by kaitlyn-sharo** [comment]
> This might have already been there and I didn't notice it (in other words, not part of this ticket), but in RQ1 Data's chart, the "Delegation preference" columns (both A/B and A/M) have some values of y and n. Maybe this has to do with the Note in the definition: "Note: response backfilled to ADMs in the same block to aid in calculation of chosen or not chosen RQ3.2" But it's a little weird to see y and n when you're expecting A and B. I imagine there's nothing to be done.

Jennifer said to use y and n, as in "y": yes, this ADM was chosen during the delegation or "n": no, this ADM was not chosen during the delgation

**Comment by nextcen-dgemoets** [comment]
More relevant to this ticket, perhaps, is that there are no session_ids when the `ADM_Type` is "comparison".  I imagine this is expected/explainable.  The data dictionary ("Definitions" table) has a blank definition for `ADM_Type`, but says the levels (values?) are Baseline or Aligned.

**Comment by kaitlyn-sharo** [comment]
> Slightly more relevant to this ticket, perhaps, is that there are no session_ids when the `ADM_Type` is "comparison". I imagine this is expected/explainable. The data dictionary ("Definitions" table) has a blank definition for `ADM_Type`, but says the levels (values?) are Baseline or Aligned.

Also something Jennifer said to do. She had considered having "comparison" as the adm type for comparison pages, but that's not an adm type, it's a page type, so we leave it blank because it's baseline and aligned being compared

**Comment by nextcen-dgemoets** [comment]
The various session IDs should be added to the various pop-up Definitions tables.  Several of these tables are also missing other fields-- especially RQ2.2 & 2.3 Data-- some of which would explain what's going on with these tables.  But other than the session IDs, it's not specifically about this ticket.

**Comment by kaitlyn-sharo** [comment]
> The various session IDs should be added to the various pop-up Definitions tables. Several of these tables are also missing other fields-- especially RQ2.2 & 2.3 Data-- some of which would explain what's going on with these tables. But other than the session IDs, it's not specifically about this ticket.

I already made a ticket for this. I cannot change it until Jennifer updates the pdfs. What other fields are missing?

**Comment by nextcen-dgemoets** [comment]
>  What other fields are missing?

At least on my local version, RQ1 and RQ3's Variable Definitions table has empty definitions for `Delegator_grp`, `Attribute`, `TA2_Name`, and `ADM_Type`.  Also, `Server Session ID (Delegator)` isn't in these tables.  It may be obvious what many of these are, but it's nice to fill it out for completeness, IMO.

In RQ2.2 & 2.3's Variable Definitions table, every definition is blank except for `Trial_ID`, and there is no column for the new `Aligned Server Session ID` and `Baseline Server Session ID`.

**Comment by kaitlyn-sharo** [comment]
> > What other fields are missing?
> 
> At least on my local version, RQ1 and RQ3's Variable Definitions table has empty definitions for `Delegator_grp`, `Attribute`, `TA2_Name`, and `ADM_Type`. Also, `Server Session ID (Delegator)` isn't in these tables. It may be obvious what many of these are, but it's nice to fill it out for completeness, IMO.
> 
> In RQ2.2 & 2.3's Variable Definitions table, every definition is blank except for `Trial_ID`, and there is no column for the new `Aligned Server Session ID` and `Baseline Server Session ID`.

As we discussed on Teams, as long as this matches the downloads that Jennifer created (which in the other reviews, everyone confirmed that, and nothing has changed since then), there is no action to take here

**Comment by nextcen-dgemoets** [comment]
> > At least on my local version, RQ1 and RQ3's Variable Definitions table has empty definitions for `Delegator_grp`, `Attribute`, `TA2_Name`, and `ADM_Type`. Also, `Server Session ID (Delegator)` isn't in these tables. It may be obvious what many of these are, but it's nice to fill it out for completeness, IMO.
> > In RQ2.2 & 2.3's Variable Definitions table, every definition is blank except for `Trial_ID`, and there is no column for the new `Aligned Server Session ID` and `Baseline Server Session ID`.
> 
> As we discussed on Teams, as long as this matches the downloads that Jennifer created (which in the other reviews, everyone confirmed that, and nothing has changed since then), there is no action to take here

What about adding `Server Session ID (Delegator)` to the table, which was added for this PR--  even if we don't have a definition yet?  Or is that covered in some other ticket?  At a basic level, it's like updating the docs for the changes covered in a PR, but as long as it's covered in some other ticket, that's fine.

**Comment by kaitlyn-sharo** [comment]
> > > At least on my local version, RQ1 and RQ3's Variable Definitions table has empty definitions for `Delegator_grp`, `Attribute`, `TA2_Name`, and `ADM_Type`. Also, `Server Session ID (Delegator)` isn't in these tables. It may be obvious what many of these are, but it's nice to fill it out for completeness, IMO.
> > > In RQ2.2 & 2.3's Variable Definitions table, every definition is blank except for `Trial_ID`, and there is no column for the new `Aligned Server Session ID` and `Baseline Server Session ID`.
> > 
> > 
> > As we discussed on Teams, as long as this matches the downloads that Jennifer created (which in the other reviews, everyone confirmed that, and nothing has changed since then), there is no action to take here
> 
> What about adding `Server Session ID (Delegator)` to the table, which was added for this PR-- even if we don't have a definition yet? Or is that covered in some other ticket? At a basic level, it's like updating the docs for the changes covered in a PR, but as long as it's covered in some other ticket, that's fine.

As I mentioned before, I have a ticket for updating the variables for these graphs.

**Comment by nextcen-dgemoets** [comment]
I see.  I thought the ticket was for the things that don't specifically pertain to this ticket.

**Review by nextcen-dgemoets — APPROVED** [review]

**Review by dereknop — APPROVED** [review]
Nice job on these tables, I see the server session ids populating

**Pull request merged**
