### PR TITLE
Itm 578

### PR DESCRIPTION
**Pull request by dereknop**
To test, pick any participant from the `participantLog` and use their PID to go through the text-based scenarios. Afterwards, check that `userScenarioResults` has gained 5 new documents. Check for the field `mostLeastAligned`. This field should contain ordered alignment scores of all the possible targets for each scenario, from most to least aligned. 

Note: the SoarTech scores are generated from that scenario on its own, the Adept scores are generated from a combination of the three scenarios

### CODE REVIEW

**Review by kaitlyn-sharo — APPROVED** [review]
Just some notes:
1. All of my adept mostLeastAligned entries are empty
2. The adept combinedAlignmentData is not ordered from least to greatest

**Comment by dereknop** [comment]
> Just some notes:
> 
> 1. All of my adept mostLeastAligned entries are empty
> 2. The adept combinedAlignmentData is not ordered from least to greatest

`combinedAlignmentData` is just intended to be all of the alignment targets and their scores. `mostLeastAligned` is probably the field that should be used on the survey. Although, I can add something real quick that sorts `combinedAlignmentData` by scores. Which URL are you using for adept? I cloned their repo and used it locally and it worked fine for me.

**Comment by kaitlyn-sharo** [comment]
> > Just some notes:
> > 
> > 1. All of my adept mostLeastAligned entries are empty
> > 2. The adept combinedAlignmentData is not ordered from least to greatest
> 
> `combinedAlignmentData` is just intended to be all of the alignment targets and their scores. `mostLeastAligned` is probably the field that should be used on the survey. Although, I can add something real quick that sorts `combinedAlignmentData` by scores. Which URL are you using for adept? I cloned their repo and used it locally and it worked fine for me.

I already made a function that sorts through combinedAlignment to get the highest and least for me. I'm using their production server and didn't get any errors in the console. Aside from the sorting, what would be the difference between the combinedAlignmentData and mostLeastAligned?

**Comment by nextcen-dgemoets** [comment]
> > Just some notes:
> > 
> > 1. All of my adept mostLeastAligned entries are empty
> 
> Which URL are you using for adept? I cloned their repo and used it locally and it worked fine for me.

Maybe Kaitlyn has the redacted scenarios and you were using the unredacted ones?

**Comment by dereknop** [comment]
> > > Just some notes:
> > > 
> > > 1. All of my adept mostLeastAligned entries are empty
> > > 2. The adept combinedAlignmentData is not ordered from least to greatest
> > 
> > 
> > `combinedAlignmentData` is just intended to be all of the alignment targets and their scores. `mostLeastAligned` is probably the field that should be used on the survey. Although, I can add something real quick that sorts `combinedAlignmentData` by scores. Which URL are you using for adept? I cloned their repo and used it locally and it worked fine for me.
> 
> I already made a function that sorts through combinedAlignment to get the highest and least for me. I'm using their production server and didn't get any errors in the console. Aside from the sorting, what would be the difference between the combinedAlignmentData and mostLeastAligned?

Nothing, this is what we talked about in the teams chat with Brian and Jennifer yesterday. Using their new endpoint was insurance that we are getting the right scores.

**Comment by kaitlyn-sharo** [comment]
> > > > Just some notes:
> > > > 
> > > > 1. All of my adept mostLeastAligned entries are empty
> > > > 2. The adept combinedAlignmentData is not ordered from least to greatest
> > > 
> > > 
> > > `combinedAlignmentData` is just intended to be all of the alignment targets and their scores. `mostLeastAligned` is probably the field that should be used on the survey. Although, I can add something real quick that sorts `combinedAlignmentData` by scores. Which URL are you using for adept? I cloned their repo and used it locally and it worked fine for me.
> > 
> > 
> > I already made a function that sorts through combinedAlignment to get the highest and least for me. I'm using their production server and didn't get any errors in the console. Aside from the sorting, what would be the difference between the combinedAlignmentData and mostLeastAligned?
> 
> Nothing, this is what we talked about in the teams chat with Brian and Jennifer yesterday. Using their new endpoint was insurance that we are getting the right scores.

Okay, that's what I thought. Was just curious why you said I should use mostLeastAligned instead of combinedAlignmentData. I'm already done, so I won't change anything

**Comment by nextcen-dgemoets** [comment]
When I ran with local TA1 servers, I got `mostLeastAligned` from both TA1s.  When I pointed to AWS, only ST scenarios had a `mostLeastAligned`.  Maybe we should redeploy the ADEPT TA1 server and try again?

**Comment by phile-caci** [comment]
> When I ran with local TA1 servers, I got `mostLeastAligned` from both TA1s. When I pointed to AWS, only ST scenarios had a `mostLeastAligned`. Maybe we should redeploy the ADEPT TA1 server and try again?

redeployed Adept Server, trying again also...

**Review by nextcen-dgemoets — APPROVED** [review]
AWS ADEPT now has `mostLeastAligned` data!
Looks good to me.

**Pull request merged**
