### PR TITLE
Itm 467

### PR DESCRIPTION
**Pull request by dereknop**
When the text-based scenarios are completed, we send all of the user choices to the TA1 servers to obtain alignment scores. 

Note:
- Going through the text-based scenarios should create 4 entries in the `userScenarioResults` collection (one for each scenario).
- Each of these documents should have a separate high and low alignment
- You must pull a fresh copy from [adept's server repo](https://gitlab.com/itm-ta1-adept-shared/adept_server) since the change to make this functional just got merged in last night 
- For future scenarios, this will be a lot cleaner, the `problemProbes.json` is needed to map MRE decisions to proper probe choices. Another function inside `TextBasedScenarios.jsx` named `mapAnswers` will not be necessary for the dry run. 

To test:
Run through the text-based scenarios and ensure your answers are properly recorded in the `userScenarioResults` collection of mongo and are accompanied by a high and low alignment score. Be sure to have the TA1 servers running locally and that you are using the dev `.env` variables and not prod. You will most-likey have to rebuild your dashboard docker container.

### CODE REVIEW

**Comment by nextcen-dgemoets** [comment]
> I branched off of Kaitlyn's feature branch to avoid merge conflicts. Only the changes to the following files are relevant to this pr: .env, TextBasedScenariosPage.jsx, problemProbes.json

You could make the PR merge into `itm-464-mongo-config` if you like.  But we can figure it out either way.  :)

**Comment by dereknop** [comment]
> > I branched off of Kaitlyn's feature branch to avoid merge conflicts. Only the changes to the following files are relevant to this pr: .env, TextBasedScenariosPage.jsx, problemProbes.json
> 
> You could make the PR merge into `itm-464-mongo-config` if you like. But we can figure it out either way. :)

Fair, I just figured I'd wait for her branch to get merged in before I merge

**Review by kaitlyn-sharo — APPROVED** [review]
Works great! I did notice there's an "alignmentData" field that's an empty string. Not sure if you want to keep that or remove it, but that was the only thing

For other reviewers, if you typically run the adept server on 8081, either change it in the .env or run on 8080.

**Comment by nextcen-dgemoets** [comment]
Well, I thought I would try this on the off-chance that I could get it configured to work right.
I pulled the latest adept and soartech repos, started them both, pulled the ITM-467 branch, ran `bash startup-scripts/dev_dashboard_ui.sh`, and completed the text scenarios (which I'm not sure I'd ever tried before).

As soon as I finished, I saw activity in both the SoarTech and Adept windows, but refreshing the database, I didn't see any new entries in the `userScenarioResults` table.

The only anomaly I'll note is that when rebuilding the dashboard, there was a very looooooooong pause at one point (I almost canceled it), then it said:
```
 Container dashboard-mongo  Running
 Container dashboard-graphql  Running
 Container dashboard-ui  Recreate
 Container dashboard-ui  Recreated
 Container dashboard-ui  Starting
 Container dashboard-ui  Started
```

The Recreate and Recreated looked a little unfamiliar.

**Comment by kaitlyn-sharo** [comment]
>there was a very looooooooong pause at one point (I almost canceled it):


Just a thought - this might be from new dependencies added since the last time you ran it. I'm not an expert on this, but I know that when it has to install the new dependencies it takes FOREVER

**Comment by nextcen-dgemoets** [comment]
Yep, the problem was "test" being in the participant ID.

Looked good.  One question-- there's a lot of empty data in the questions object, e.g. all of the "[...] Vitals" and "Probe x-x" fields just have `{}` as values.

**Comment by nextcen-dgemoets** [comment]
> Works great! I did notice there's an "alignmentData" field that's an empty string. Not sure if you want to keep that or remove it, but that was the only thing

I dumped my output to a JSON file and I didn't see any empty `alignmentData` fields.

**Comment by dereknop** [comment]
> Yep, the problem was "test" being in the participant ID.
> 
> Looked good. One question-- there's a lot of empty data in the questions object, e.g. all of the "[...] Vitals" and "Probe x-x" fields just have `{}` as values.

Yeah that's because any place in the text-based scenarios where it has the tables with patient vitals is technically a custom question type I had to make for it to be embedded in the survey. Just a clunky thing with the SurveyJS library. So there is no possible data to be in those spots.

**Review by nextcen-dgemoets — APPROVED** [review]
Looks good!

**Pull request merged**
