### PR TITLE
Updates to RQ tables

### PR DESCRIPTION
**Pull request by kaitlyn-sharo**
After running https://github.com/NextCenturyCorporation/itm-ingest/pull/94:
1. Go to the RQ1/3/4 tables and see that it is the same for DRE and Phase 1 as it was before
2. With the Phase 1 drop down selected, toggle on DRE data
3. See that Alignment Score (Delegator|ObservedADM) (target) is now different for Adept in DRE than it was when you had the DRE drop-down selected
4. The DRE data should be different FOR ADEPT ONLY, and we expect everything to be populated
5. The Phase 1 data should stay the same

Additional changes:
- DRE-research is now just research (directory name change)
- dre-results is now research-results in the url
- RQ8 shows sim kdmas

### CODE REVIEW

**Review by nextcen-dgemoets — COMMENTED** [review]
Everything was exactly as you described.  I have no further insights into other things I should have checked.

You'll hate me for it, but I have to report that the RQ8 variable definitions still say `Participant KDMA` and don't include `Participant Sim KDMA`.

**Comment by kaitlyn-sharo** [comment]
> Everything was exactly as you described. I have no further insights into other things I should have checked.
> 
> You'll hate me for it, but I have to report that the RQ8 variable definitions still say `Participant KDMA` and don't include `Participant Sim KDMA`.

I thought that was self-explanatory

**Comment by nextcen-dgemoets** [comment]
> > Everything was exactly as you described. I have no further insights into other things I should have checked.
> > You'll hate me for it, but I have to report that the RQ8 variable definitions still say `Participant KDMA` and don't include `Participant Sim KDMA`.
> 
> I thought that was self-explanatory

Sure, I doubt anybody will be lost without these changes.  But I think the column name should be updated and the new column added for completeness.  I know that editing the downloaded definitions is tedious/time-consuming, so maybe that can be deferred.  In any event, I'm not going to withhold my approval of the PR on these grounds.

**Review by nextcen-dgemoets — APPROVED** [review]

**Comment by kaitlyn-sharo** [comment]
> > > Everything was exactly as you described. I have no further insights into other things I should have checked.
> > > You'll hate me for it, but I have to report that the RQ8 variable definitions still say `Participant KDMA` and don't include `Participant Sim KDMA`.
> > 
> > 
> > I thought that was self-explanatory
> 
> Sure, I doubt anybody will be lost without these changes. But I think the column name should be updated and the new column added for completeness. I know that editing the downloaded definitions is tedious/time-consuming, so maybe that can be deferred. In any event, I'm not going to withhold my approval of the PR on these grounds.

Updated (but not the download)

**Review by phile-caci — COMMENTED** [review]
Everything looks good to me... just a question on the 'Alignment score (Participant_sim|Observed_ADM(target))' (RQ1|3), were they supposed to change?

(I was using last nights backup when I ran through all the ingest tickets)

On my local after running through all the ingest:
image

On Prod:
image

**Comment by kaitlyn-sharo** [comment]
> Everything looks good to me... just a question on the 'Alignment score (Participant_sim|Observed_ADM(target))' (RQ1|3), were they supposed to change?
> 
> (I was using last nights backup when I ran through all the ingest tickets)
> 
> On my local after running through all the ingest: image
> 
> On Prod: image

They were not! I think I see the problem there, thanks for catching that!

**Comment by kaitlyn-sharo** [comment]
Updated by deleting the extra mistake line that was changing Participant_sim|Observed_ADM(target)

**Review by phile-caci — APPROVED** [review]
LGTM!

**Pull request merged**
